### ISSUE TITLE
Doesn't work with Node 6.

### ISSUE THREAD

**Issue by ACPK** [twokul/yam#13]
deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
graceful-fs@3.0.8 node_modules/yam/node_modules/graceful-fs -> node_modules/ember-cli/node_modules/graceful-fs

**Comment by twokul** [comment]
addressed in https://github.com/twokul/yam/commit/1d65ed9c005b55ce3810ecc76d953f81db282473
